# Dataset configuration for GRG detection
DATASET_NAME: "grg"
DATA_ROOT: "/home/s4861264/project_data/split"

TRAIN:
  EXISTS: True
  NAME: "train"
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"

VALIDATION:
  EXISTS: True
  NAME: "val"
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"

TEST:
  EXISTS: True
  NAME: "test"
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"
